# These substitutions allow the end user to override certain values
substitutions:
  name: "bme280-sensor"

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  platform: ESP8266
  board: d1_mini

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: crblackw.bme280-sensor
    version: "1.0.1"

# Enable logging
logger:

# Enable Home Assistant API
api:

# OTA is required for Over-the-Air updating
ota:

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://crblackw/esphome-bme280-sensor/bme280-sensor.yaml@v1.0.1

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Envsensor Fallback Hotspot"
    password: "envsensor101"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

i2c:

sensor:
  # Light sensor config
  - platform: adc
    pin: A0
    name: "Outside Brightness"
  # Environment sensor config
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      id: bme280_temperature
    pressure:
      name: "BME280 Pressure"
      id: bme280_pressure
    humidity:
      name: "BME280 Relative Humidity"
      id: bme280_humidity
    address: 0x76
    update_interval: 60s
